# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Asterisk server virtual machine specs configuration
    config.vm.define "asterisk" do |asterisk|
      asterisk.vm.box = "ubuntu/trusty64"
      asterisk.vm.hostname = "asterisk"
      asterisk.vm.network "public_network"
      asterisk.vm.network "forwarded_port", guest: 80, host: 8080
      asterisk.vm.synced_folder "../sync", "/root/sync", create: true

      asterisk.vm.provider "virtualbox" do |vb|
        vb.name = "asterisk"
        vb.memory = 512
        # vb.gui = true
      end

      asterisk.vm.provision "shell", inline: <<-SHELL

      echo "SETTING UP ASTERISK SERVER"

      echo "Update apt-get and install essential software"
      sudo apt-get -y update > /dev/null
      echo "apt-get updated"
      sudo apt-get install -y build-essential > /dev/null
      echo "build-essential installed"
      sudo apt-get install -y git > /dev/null
      echo "git installed"
      sudo apt-get install -y asterisk > /dev/null
      echo "asterisk"

      echo "Asterisk Status:"
      sudo service asterisk status

      echo "ASTERISK SERVER IS READY"

      SHELL
    end
end
